token_custom.type.*:
  type: config_object
  label: 'Custom Token Type'
  mapping:
    uuid:
      type: string
      label: UUID
    status:
      type: boolean
      label: Status
    dependencies:
      type: sequence
      label: Dependencies
    machineName:
      type: string
      label: 'Machine Name'
    name:
      type: string
      label: 'Name'
    description:
      type: string
      label: 'Description'
